### ISSUE TITLE
Tag 3.0.8 is broken

### ISSUE THREAD

**Issue by Sebobo** [neos/content-repository-search#45]
It only allows older version of Neos. 3.0.7 is more up-to-date.

I assume the 3.0 branch was not up merged before the last patch was merged and tagged.

**Comment by markusguenther** [comment]
<img width="889" alt="Screenshot 2021-11-19 at 10 57 44" src="https://user-images.githubusercontent.com/1014126/142605105-386dcb36-efa2-452e-ba6a-0d086f338e94.png">
<img width="873" alt="Screenshot 2021-11-19 at 10 57 51" src="https://user-images.githubusercontent.com/1014126/142605109-bc4cda2d-aa4e-4567-b31d-aea41fd48e48.png">
We have an dependency issue here. Don´t know why but so no one can update to 3.0.8 when they use flow 5.3.

**Comment by kdambekalns** [comment]
Yes, because 3.0.8 was actually created off of `master`

**Comment by markusguenther** [comment]
As this triggered me a bit, I choose now the way to update the package so that we get a version 3.0.9 that is compatible with flow 4 and 5.

The circumstances that the package was available for some versions leads to the issue that users with neos 4.3 that upgrades to PHP 7.4 now needs version 3.0.8, but that is not available by the version constraint to flow 4.

My other path to just use 4.0 leads to a trap as the flowpack search plugin does not have the right constraints to version 4.0 and it also does not works as the interface of the QueryBuilder changed a bit (type safety stuff).

So, I would like to release a version 3.0.9 so that the people (will be not that much) can use PHP 7.4 without deprecation warnings until the upgrade to Neos 5.3 or 7.3 :)

https://github.com/Flowpack/Flowpack.SearchPlugin/pull/71

**Comment by kdambekalns** [comment]
See #49
